---
- template: src=templates/resolv.conf.j2 dest=/etc/resolv.conf owner=root group=root mode=0644
  when: ansible_os_family == 'RedHat'

- template: src=templates/resolvconf.tail.j2 dest=/etc/resolvconf/resolv.conf.d/tail owner=root group=root mode=0644
  when: ansible_os_family == 'Debian'
